version: '3'

services:
  logstash:
    image: logstash:6.5.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
    environment:
      LOG_LEVEL: info
    ports:
      - 5044:5044
