version: '3'

services:
  kibana:
    image: kibana:6.5.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - "LOGGING_QUIET=true"
    ports:
      - 5601:5601