## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/master/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.js
server.name: kibana
elasticsearch.url: http://85.214.125.128:9200
xpack.monitoring.ui.container.elasticsearch.enabled: true

## X-Pack security credentials
elasticsearch.username: elastic
elasticsearch.password: changeme
