version: '3'
services:
  filebeat_1:
    volumes:
      - /user/filebeat_1/logs:/user/logs/
    build:
      context: ./filebeat/
      dockerfile: Dockerfile
    
  elkicient_app_1:
    volumes:
      - /user/filebeat_1/logs:/home/gradle/project/logs
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8081:8080"    
  
  filebeat_2:
    volumes:
      - /user/filebeat_2/logs:/user/logs
    build:
      context: ./filebeat/
      dockerfile: Dockerfile
      
  elkicient_app_2:
    volumes:
      - /user/filebeat_2/logs:/home/gradle/project/logs
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "8082:8080"